spring.application.name=demo

spring.datasource.url=jdbc:h2:file:./data/biddingdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2

app.security.admin.username=admin
app.security.admin.password=admin
app.security.bidder.username=bidder
app.security.bidder.password=bidder
app.security.auctioneer.username=auctioneer
app.security.auctioneer.password=auctioneer
