ALTER TABLE IF EXISTS items
ADD COLUMN IF NOT EXISTS condition VARCHAR(40);

ALTER TABLE IF EXISTS items
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;

UPDATE items
SET condition = 'NEW'
WHERE condition IS NULL;

ALTER TABLE IF EXISTS items
ALTER COLUMN condition SET DEFAULT 'NEW';
