package com.ccbid.biddingsite.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.ccbid.biddingsite.dataStructures.ItemBid;
import com.ccbid.biddingsite.dto.ActiveBidSummaryResponse;
import com.ccbid.biddingsite.dto.BidHistorySummaryResponse;
import com.ccbid.biddingsite.dto.ListItemRequest;
import com.ccbid.biddingsite.dto.ListItemResponse;
import com.ccbid.biddingsite.dto.PlaceBidRequest;
import com.ccbid.biddingsite.models.ItemCondition;
import com.ccbid.biddingsite.models.ListingDurationUnit;
import com.ccbid.biddingsite.models.UserAccount;
import com.ccbid.biddingsite.service.AuthService;
import com.ccbid.biddingsite.service.BidService;

/**
 * This is the controller for handling all the bid requests
 * Important Methods:
 * List Item: Allows an auctioneer to list an item for bidding
 * Place Bid: Allows a bidder to place a bid on an item
 * Get Highest: Returns the highest bid and bidder for an item
 * Remove Own Bid: Allows a bidder to remove their own bid from an item, in case of mistakes or changing their mind over time, might introduce a small fee for this
 * Remove Bid: Allows an admin to remove any bid from an item, for occassional trolls or rate limiters
 * Exception Handlers: Handles exceptions for bad requests and conflicts (This was generated by Codex with the prompt "I'm recieving errors about handling a certain exception how do I approach this")
 */

@RestController
@RequestMapping("/bid")
public class BidController {

    @Autowired
    private BidService service;

    @Autowired
    private AuthService authService;

    @PostMapping("/list")
    public ListItemResponse listItem(Authentication authentication, @RequestBody ListItemRequest req) {
        UserAccount account = authService.getRequiredAccount(authentication.getName());
        ItemBid bid = service.addItem(
            req.itemName(),
            req.startingPrice(),
            req.description(),
            parseCondition(req.condition()),
            parseDurationAmount(req.durationAmount()),
            parseDurationUnit(req.durationUnit()),
            account.getUsername(),
            account.getDisplayName()
        );
        return new ListItemResponse(
            bid.getItem().getItemId(),
            bid.getItem().getItemName(),
            bid.getAuctioneer().getAuctioneerId(),
            bid.getAuctioneer().getName(),
            bid.getItem().getExpiresAt(),
            "Listed " + bid.getItem().getItemId() + " (" + bid.getItem().getItemName()
                + ") by auctioneer " + bid.getAuctioneer().getAuctioneerId()
        );
    }

    @PostMapping("/{itemId}")
    public String placeBid(Authentication authentication,
                           @PathVariable String itemId,
                           @RequestBody PlaceBidRequest req) {
        if (req.amount() == null) {
            throw new IllegalArgumentException("amount is required");
        }
        if (req.bidderId() != null && !req.bidderId().isBlank() && !req.bidderId().equals(authentication.getName())) {
            throw new IllegalArgumentException("Authenticated user does not match bidderId");
        }
        return service.placeBid(itemId, authentication.getName(), req.amount());
    }

    @GetMapping("/{itemId}/highest")
    public String getHighest(@PathVariable String itemId) {
        String bidder = service.getHighestBidder(itemId);
        int amount = service.getHighestBid(itemId);
        if (bidder == null) {
            return "No bids on " + itemId;
        }
        return "Highest on " + itemId + ": " + bidder + " @ " + amount;
    }

    @GetMapping("/active")
    public Iterable<ActiveBidSummaryResponse> getActiveBids(Authentication authentication) {
        if (isAdmin(authentication)) {
            return service.getAllActiveBidSummaries();
        }
        if (hasRole(authentication, "ROLE_AUCTIONEER")) {
            return service.getActiveBidSummariesForAuctioneer(authentication.getName());
        }
        return service.getActiveBidSummariesForBidder(authentication.getName());
    }

    @GetMapping("/history")
    public Iterable<BidHistorySummaryResponse> getBidHistory(Authentication authentication) {
        if (isAdmin(authentication)) {
            return service.getAllBidHistory();
        }
        if (hasRole(authentication, "ROLE_AUCTIONEER")) {
            return service.getBidHistoryForAuctioneer(authentication.getName());
        }
        return service.getBidHistoryForBidder(authentication.getName());
    }

    @GetMapping("/expired")
    public Iterable<BidHistorySummaryResponse> getExpiredBidOutcomes() {
        return service.getExpiredBidOutcomes();
    }

    @DeleteMapping("/{itemId}")
    public String removeOwnBid(Authentication authentication,
                               @PathVariable String itemId) {
        return service.removeBid(itemId, authentication.getName());
    }

    @DeleteMapping("/{itemId}/{bidderId}")
    public String removeBid(Authentication authentication,
                            @PathVariable String itemId,
                            @PathVariable String bidderId) {
        if (!isAdmin(authentication) && !authentication.getName().equals(bidderId)) {
            throw new IllegalArgumentException("Authenticated user does not match bidderId");
        }
        String effectiveBidderId = isAdmin(authentication) ? bidderId : authentication.getName();
        return service.removeBid(itemId, effectiveBidderId);
    }

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<String> handleBadRequest(IllegalArgumentException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }

    @ExceptionHandler(IllegalStateException.class)
    public ResponseEntity<String> handleConflict(IllegalStateException e) {
        return ResponseEntity.status(HttpStatus.CONFLICT).body(e.getMessage());
    }

    private boolean isAdmin(Authentication authentication) {
        return hasRole(authentication, "ROLE_ADMIN");
    }

    private boolean hasRole(Authentication authentication, String role) {
        return authentication.getAuthorities().stream()
            .anyMatch(authority -> role.equals(authority.getAuthority()));
    }

    private ItemCondition parseCondition(String condition) {
        if (condition == null || condition.isBlank()) {
            throw new IllegalArgumentException("condition is required");
        }
        try {
            return ItemCondition.valueOf(condition.trim().toUpperCase().replace(' ', '_'));
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("condition must be NEW, USED, or HIGHLY_DAMAGED");
        }
    }

    private int parseDurationAmount(Integer durationAmount) {
        if (durationAmount == null || durationAmount < 1) {
            throw new IllegalArgumentException("durationAmount must be at least 1");
        }
        return durationAmount;
    }

    private ListingDurationUnit parseDurationUnit(String durationUnit) {
        if (durationUnit == null || durationUnit.isBlank()) {
            throw new IllegalArgumentException("durationUnit is required");
        }
        try {
            return ListingDurationUnit.valueOf(durationUnit.trim().toUpperCase().replace(' ', '_'));
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("durationUnit must be HOURS, DAYS, WEEKS, or MONTHS");
        }
    }
}
